# site settings
title: Bio Mama
subtitle: by Sedi
email: s.fazli21@gmail.com
description: I am here to start fresh <br /> Strong enough to not give up
url: https://sedi-datascience-journey.github.io/bio-mama-blog/ # the base hostname & protocol for your site
author: Sedi
city: Portland
state: OR
country: United States of America


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/sedi-datascience-journey
  GitLab:
  Instagram: https://www.instagram.com/sedi3336/
  LinkedIn: www.linkedin.com/in/sedifazli
  

# build settings
markdown: kramdown

sass:
  style: compressed
